# MOREA CONFIGURATION FILE
# See https://morea-framework.github.io/docs/instructors/config-yml

# SITE SPECIFIC: The following fields are typically changed for each site
name: LV-uav-workflow
baseurl: /LV-uav-workflow
morea_theme: cerulean-purple
timezone: Europe/Berlin
morea_navbar_items:
  - Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
logger_factory:
  Morea: error

markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
exclude: [morea]
keep_files: [schedule/schedule-info.js]
plugins:
  - jekyll-gist